### ISSUE TITLE
projectURL in adoc-Dateien

### ISSUE THREAD

**Issue by DebXWoody** [vlug-hessen/vlug-hessen-web#10]
Ich habe die Projektseiten der Homepage auf adoc umgestellt. In diesen Dateien ist ein Eintrag

`:jbake-projectURL: https://github.com/vlug-hessen/vlug-sandbox
`

Die Projekt-URL wird jedoch nicht angezeigt. Siehe Beispiel: http://www.vlug-hessen.de/project/vlug-sandbox.html

website und git werden angezeigt.

**Comment by ancho** [comment]
Das ist interessant. Habe es mir kurz angeschaut. lässt man das URL weg und passt das template entsprechend an, funktioniert es. Ein seltsamer Bug. Herzlichen Glückwunsch. Wenn du magst kannst du im jbake Projekt ein Issue dazu erstellen.

Ich schicke gleich nen fix für die Webseite.

**Comment by ancho** [comment]
Erledigt durch workaround #11
