### ISSUE TITLE
Homepage auf Github verschieben

### ISSUE THREAD

**Issue by DebXWoody** [vlug-hessen/vlug-hessen-web#4]
Aktuell haben wir die Homepage noch in einem anderen Repository. Wir wollen die Homepage jetzt auch hier verwalten.

- [x] Wir nehmen die Mitgliederseite von der Homepage raus
- [x] Den Code auf den aktullen Stand bringen

**Comment by DebXWoody** [comment]
Wer will denn diesen Issue übernehmen?

**Comment by ancho** [comment]
Mit Mitgliederseite raus nehmen meinst du `members.adoc` und `members/*`?

**Comment by DebXWoody** [comment]
Js
